services:
  api:
    build:
      context: .
      dockerfile: src/Bootstrap/Api/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Username=postgres;Password=postgres;Database=oficina_mecanica;SSL Mode=Disable
      - Jwt__Secret=docker-dev-secret-key-replace-in-prod-00
      - Auth__AdminEmail=admin@oficina.com
      - Auth__AdminSenha=admin123
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: always
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: oficina_mecanica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
