<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Autenticacao\Autenticacao.Infrastructure\Autenticacao.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Autenticacao\Autenticacao.Presentation\Autenticacao.Presentation.csproj" />
    <ProjectReference Include="..\..\Modules\Cadastro\Cadastro.Infrastructure\Cadastro.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Cadastro\Cadastro.Web\Cadastro.Web.csproj" />
    <ProjectReference Include="..\..\Modules\PecasInsumos\PecasInsumos.Infrastructure\PecasInsumos.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\PecasInsumos\PecasInsumos.Web\PecasInsumos.Web.csproj" />
    <ProjectReference Include="..\..\Modules\OrdensServico\OrdensServico.Infrastructure\OrdensServico.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\OrdensServico\OrdensServico.Presentation\OrdensServico.Presentation.csproj" />
    <ProjectReference Include="..\..\SharedKernel\SharedKernel.Application\SharedKernel.Application.csproj" />
  </ItemGroup>

</Project>
