<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SharedKernel\SharedKernel.Application\SharedKernel.Application.csproj" />
    <ProjectReference Include="..\..\OrdensServico\OrdensServico.Contracts\OrdensServico.Contracts.csproj" />
    <ProjectReference Include="..\PecasInsumos.Contracts\PecasInsumos.Contracts.csproj" />
    <ProjectReference Include="..\PecasInsumos.Domain\PecasInsumos.Domain.csproj" />
  </ItemGroup>

</Project>
