<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cadastro\Cadastro.Contracts\Cadastro.Contracts.csproj" />
    <ProjectReference Include="..\..\PecasInsumos\PecasInsumos.Contracts\PecasInsumos.Contracts.csproj" />
    <ProjectReference Include="..\OrdensServico.Application\OrdensServico.Application.csproj" />
    <ProjectReference Include="..\OrdensServico.Domain\OrdensServico.Domain.csproj" />
  </ItemGroup>

</Project>
