apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina-mecanica
  labels:
    app.kubernetes.io/part-of: oficina-mecanica
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  Auth__AdminEmail: "admin@oficina.com"
