apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: oficina-mecanica
  labels:
    app.kubernetes.io/part-of: oficina-mecanica
type: Opaque
stringData:
  POSTGRES_USER: "oficina"
  POSTGRES_PASSWORD: "oficina-cluster-pass-000"
  POSTGRES_DB: "oficina_mecanica"
  ConnectionStrings__Default: "Host=oficina-postgres;Port=5432;Username=oficina;Password=oficina-cluster-pass-000;Database=oficina_mecanica;SSL Mode=Disable"
  Jwt__Secret: "cluster-jwt-secret-key-min-32-chars-000"
  Auth__AdminSenha: "admin123"
