// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrdensServico.Infrastructure.Persistence;

#nullable disable

namespace OrdensServico.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrdensServicoDbContext))]
    partial class OrdensServicoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ordem_servico")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrdensServico.Domain.OrdemServico.ItemPeca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PecaInsumoId")
                        .HasColumnType("uuid")
                        .HasColumnName("peca_insumo_id");

                    b.Property<decimal>("PrecoUnitarioSnapshot")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_unitario_snapshot");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("ordem_servico_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ordem_servico_id");

                    b.ToTable("os_peca", "ordem_servico");
                });

            modelBuilder.Entity("OrdensServico.Domain.OrdemServico.ItemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("PrecoUnitarioSnapshot")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_unitario_snapshot");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("ServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("servico_id");

                    b.Property<Guid>("ordem_servico_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ordem_servico_id");

                    b.ToTable("os_servico", "ordem_servico");
                });

            modelBuilder.Entity("OrdensServico.Domain.OrdemServico.Orcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aprovacao");

                    b.Property<DateTime?>("DataEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_envio");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_geracao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_total");

                    b.Property<Guid>("ordem_servico_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ordem_servico_id");

                    b.ToTable("orcamento", "ordem_servico");
                });

            modelBuilder.Entity("OrdensServico.Domain.OrdemServico.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescricaoDiagnostico")
                        .HasColumnType("text")
                        .HasColumnName("descricao_diagnostico");

                    b.Property<DateTime?>("EntregueEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entregue_em");

                    b.Property<DateTime?>("NotificadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("notificado_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.ToTable("ordem_servico", "ordem_servico");
                });

            modelBuilder.Entity("OrdensServico.Domain.OrdemServico.ItemPeca", b =>
                {
                    b.HasOne("OrdensServico.Domain.OrdemServico.OrdemServico", null)
                        .WithMany("ItensPeca")
                        .HasForeignKey("ordem_servico_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrdensServico.Domain.OrdemServico.ItemServico", b =>
                {
                    b.HasOne("OrdensServico.Domain.OrdemServico.OrdemServico", null)
                        .WithMany("ItensServico")
                        .HasForeignKey("ordem_servico_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrdensServico.Domain.OrdemServico.Orcamento", b =>
                {
                    b.HasOne("OrdensServico.Domain.OrdemServico.OrdemServico", null)
                        .WithMany("Orcamentos")
                        .HasForeignKey("ordem_servico_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrdensServico.Domain.OrdemServico.OrdemServico", b =>
                {
                    b.Navigation("ItensPeca");

                    b.Navigation("ItensServico");

                    b.Navigation("Orcamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
